### ISSUE TITLE
Support for installing with HACS

### ISSUE THREAD

**Issue by Herjar** [DarkSir23/sensor.mylar#1]
Would be good if this could be installed with HACS:
https://github.com/hacs/integration

**Comment by WillowMist** [comment]
Updated and submitted as a default HACS repository.

**Comment by sunjam** [comment]
Hi, what happened with this @WillowMist?  Thanks for making this integration!  Glad I was able to find your github repository, but it would be awesome if it were indexed on https://www.home-assistant.io/integrations/

Seems they can assist you on the #devs_core channel of their discord - https://www.home-assistant.io/join-chat/
And [here is developer integration documentation](https://developers.home-assistant.io/docs/development_index/)
